---
  - name: Activate Satellite repositories for RHEL
    rhsm_repository:
      name: "{{ item }}"
      state: enabled
    with_items:
      - rhel-7-server-extras-rpms
      - rhel-server-rhscl-7-rpms
      - rhel-7-server-optional-rpms
      - "{{ awx_repo }}"
      - "{{ epel_repo }}"
      - "{{ awx_dependencies_repo }}"
    when: ansible_distribution == 'Red Hat Enterprise Linux'

  - name: Add AWX Repositories for CentOS
    shell: yum-config-manager --add-repo=https://copr.fedorainfracloud.org/coprs/mrmeee/ansible-awx/repo/epel-7/mrmeee-ansible-awx-epel-7.repo
    args:
      creates: /etc/yum.repos.d/ansible-awx.repo 
    when: ansible_distribution == 'CentOS'

  - name: Add RabbitMQ Repository
    template:
      src: rabbitmq.repo.j2
      dest: /etc/yum.repos.d/rabbitmq.repo
      owner: root
      group: root
      mode: 0644
    when: ansible_distribution == 'CentOS'

  - name: Add Erlang Repository
    template:
      src: rabbitmq-erlang.repo.j2
      dest: /etc/yum.repos.d/rabbitmq-erlang.repo
      owner: root
      group: root
      mode: 0644
    when: ansible_distribution == 'CentOS'
  
  - name: Add Tower CLI Repository
    template:
      src: tower-cli.repo.j2
      dest: /etc/yum.repos.d/tower-cli.repo
      owner: root
      group: root
      mode: 0644
    when: ansible_distribution == 'CentOS'

  - name: Install packages for CentOS
    yum:
      name: "{{ packages }}"
    vars:
      packages:
        - epel-release
        - centos-release-scl
        - centos-release-scl-rh
        - yum-utils
    when: ansible_distribution == 'CentOS'

  - name: Install rh-git29
    yum:
      name: rh-git29
      state: present
    when: ansible_distribution == 'CentOS'

  - name: Install Ansible & tower-cli
    yum:
      name: 
        - ansible 
        - tower-cli
      state: present

  - name: Install RabbitMQ
    yum:
      name: rabbitmq-server
      state: present

  - name: Install Memcached
    yum:
      name: memcached
      state: present
    when: ansible_distribution == 'Red Hat Enterprise Linux'

  - name: Install PostgreSQL & Memcached
    yum:
      name: "{{ packages }}"
    vars:
      packages:
        - rh-postgresql10
        - memcached
    when: ansible_distribution == 'CentOS'

  - name: remove the PostgreSQL package
    yum:
      name: rh-postgresql10
      state: absent
    when: ansible_distribution == 'CentOS'

  - name: Install rh-python36
    yum:
      name: rh-python36
      state: present
    when: ansible_distribution == 'CentOS'

  - name: Install Python dependencies
    shell: yum -y install --disablerepo='*' --enablerepo='copr:copr.fedorainfracloud.org:mrmeee:ansible-awx, base' -x *-debuginfo rh-python36*

  - name: Install AWX
    yum:
      name: ansible-awx
      state: latest

  - name: Start & enable RabbitMQ service at boot
    service:
      name: rabbitmq-server
      state: started
      enabled: yes

  - name: Start & enable Memcached service at boot
    service:
      name: memcached
      state: started
      enabled: yes

  - name: Edit AWX configuration to connect to external DB
    lineinfile:
      path: /etc/tower/settings.py
      regexp: "{{ item.regexp }}"
      line: "{{ item.line }}"
      state: present
    with_items:
      - { regexp: "'NAME':", line: "        'NAME': 'awx'," }
      - { regexp: "'USER':", line: "        'USER': 'awx'," }
      - { regexp: "'HOST':", line: "        'HOST': '{{ groups['db'][0] }}'," }
      - { regexp: "'PORT':", line: "        'PORT': '5432'," }
      - { regexp: "'PASSWORD':", line: "        'PASSWORD': '{{ hostvars[groups['db'][0]]['password'] }}'," }

  - name: Install NGINX
    yum:
      name: nginx
      state: present

  - name: Add AWX configuration to NGINX
    template:
      src: nginx_awx.conf.j2
      dest: /etc/nginx/nginx.conf
      owner: root
      group: root
      mode: 0644

  - name: Edit SELinux to permit AWX needed ports
    seport:
      ports: 8050-8052
      proto: tcp
      setype: http_port_t
      state: present

  - name: Start & enable NGINX service at boot
    service:
      name: nginx
      state: started
      enabled: yes

  - name: Start & enable AWX services
    service:
      name: "{{ item }}"
      state: restarted
      enabled: yes
    with_items:
      - 'awx-cbreceiver'
      - 'awx-dispatcher'
      - 'awx-channels-worker'
      - 'awx-daphne'
      - 'awx-web'
